language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq python-dev libxslt1-dev libxml2-dev
install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements_test.txt"
  - "pip freeze"
script: "nosetests -v --exclude=async"
notifications:
  email: false
